name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.81ec2533-6d0e-4c48-9719-75d9d21dc262 }}
          GH_TOKEN: ${{ secrets.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 }}
    
